version: '3'

services:
  water-bot:
    image: water-bot:latest
    container_name: water-bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
    command: ./water-bot

  water-scraper:
    image: water-bot:latest
    container_name: water-scraper
    restart: always
    volumes:
      - ./data:/app/data
    command: ./water-scrapper