name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: water-bot:latest
        outputs: type=docker,dest=/tmp/water-bot.tar
        
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.DIGITALOCEAN_HOST }} >> ~/.ssh/known_hosts
        
    - name: Copy Docker image to server
      run: |
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no /tmp/water-bot.tar ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }}:/opt/water-bot/
        scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }}:/opt/water-bot/
        
    - name: Deploy to Digital Ocean
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }} "
          cd /opt/water-bot && 
          docker load -i water-bot.tar && 
          echo \"TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}\" > .env && 
          docker-compose down && 
          docker-compose up -d && 
          rm water-bot.tar && 
          echo \"Deployment completed successfully at $(date)\"
        "