name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: water-bot:latest
        outputs: type=docker,dest=/tmp/water-bot.tar
        
    - name: Copy Docker image and deployment files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
        source: "/tmp/water-bot.tar,docker-compose.yml"
        target: "/opt/water-bot"
        strip_components: 1
        
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
        script: |
          cd /opt/water-bot
          docker load -i water-bot.tar
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
          docker-compose down
          docker-compose up -d
          rm water-bot.tar
          echo "Deployment completed successfully at $(date)"